Revision: Switch To Monaco Editor
DioxusLabs/playground pull request #13
Opened 2024-09-18 01:12 UTC by DogeDark

Switches from Ace editor to the Monaco editor (the editor vscode uses)

Todo:
- [x] Get it running.
- [x] Auto theme switching.
- [ ] Get the web workers web-working.
- [ ] Handle models and rewrite editor-dependent code to use new editor.
- [ ] Remove unnecessary files.

2025-01-25 00:14 UTC, jkelleyrtp requested changes
A couple UX things to solve before we release but overall looks good!

2025-01-25 07:35 UTC, DogeDark commented on server/src/build/watcher.rs
> +        }
I actually think this should be a `continue`! The idea was to remove the pending build from the queue, and the `is_some()` was to tell all builds *after* the removed one to decrement its queue position.

2025-01-25 07:40 UTC, DogeDark commented on playground/src/share_code.rs
> +
I will create an issue for this and the other action items you presented. I thought I heard someone mention that using Gist like this might be against the GitHub TOS, so I'll see if I can find anything about that.

2025-01-25 07:49 UTC, DogeDark commented on playground/src/hotreload.rs
> +    }
I agree. I think this is something that should be implemented before any major public release. It seems like we're not officially-officially releasing the playground just yet, so this would probably be better in a relatively soon separate PR. Of course, if you want it in this PR, let me know, but I will resolve this and create an issue for it for now.

2025-01-25 07:57 UTC, DogeDark commented on playground/src/lib.rs
> +
I am not sure I understand what you mean about a fancier examples UI. Specifically, how would this work with caching examples on the server? Or is this for limited use around the docsite? In my mind, the playground is a full self-contained page on the docsite (including things like a components list, ai, or in this case, a fancier better examples UI). 

I will add this though as I think it will be useful, just need some clarification on what you want to use it for specifically.

2025-01-25 08:14 UTC, DogeDark commented
To-Do:
- [ ] Resolve Conversations
- [ ] Add some minor padding and maybe styling to iframe.
- [ ] Keep the `Run` button available at all times.

2025-01-28 00:48 UTC, DogeDark commented on playground/src/components/panes.rs
> +
It turns out it was only set to disable dragging if `mouseup` was called on the tiny 2px bar! Adding extra `mouseup` and `mouseleave` on the panes has made it much better.

2025-01-28 23:36 UTC, merged